import type { CloudPlan, CloudRegion } from './types'

/** Default EU regions for DigitalOcean-style create flow */
export const DEFAULT_REGIONS: CloudRegion[] = [
  {
    id: 'ams',
    name: 'Amsterdam',
    slug: 'ams',
    location: 'Amsterdam, Netherlands (EU West)',
    flag: '🇳🇱',
    clusterId: 0,
    networkId: 0,
    datastoreId: 1,
    available: true,
  },
  {
    id: 'fra',
    name: 'Frankfurt',
    slug: 'fra',
    location: 'Frankfurt, Germany (EU Central)',
    flag: '🇩🇪',
    clusterId: 1,
    networkId: 1,
    datastoreId: 1,
    available: true,
  },
  {
    id: 'sto',
    name: 'Stockholm',
    slug: 'sto',
    location: 'Stockholm, Sweden (EU North)',
    flag: '🇸🇪',
    clusterId: 2,
    networkId: 2,
    datastoreId: 2,
    available: true,
  },
]

/** Default VPS plans (map templateId to your OpenNebula templates in production) */
export const DEFAULT_PLANS: CloudPlan[] = [
  {
    id: 's-1vcpu-1gb',
    name: 'Basic',
    slug: 's-1vcpu-1gb',
    description: 'Good for blogs, low-traffic apps, and staging.',
    vcpus: 1,
    memoryMb: 1024,
    diskGb: 25,
    transferTb: 1,
    priceMonthlyCents: 600,
    currency: 'EUR',
    templateId: 1,
    featured: false,
  },
  {
    id: 's-2vcpu-4gb',
    name: 'General Purpose',
    slug: 's-2vcpu-4gb',
    description: 'Balanced compute for production APIs and shops.',
    vcpus: 2,
    memoryMb: 4096,
    diskGb: 80,
    transferTb: 4,
    priceMonthlyCents: 2400,
    currency: 'EUR',
    templateId: 1,
    featured: true,
  },
  {
    id: 's-4vcpu-8gb',
    name: 'CPU Optimized',
    slug: 's-4vcpu-8gb',
    description: 'Higher concurrency for databases and workers.',
    vcpus: 4,
    memoryMb: 8192,
    diskGb: 160,
    transferTb: 5,
    priceMonthlyCents: 4800,
    currency: 'EUR',
    templateId: 2,
    featured: false,
  },
  {
    id: 's-8vcpu-16gb',
    name: 'Memory Optimized',
    slug: 's-8vcpu-16gb',
    description: 'Large caches, analytics, and heavy CMS workloads.',
    vcpus: 8,
    memoryMb: 16384,
    diskGb: 320,
    transferTb: 6,
    priceMonthlyCents: 9600,
    currency: 'EUR',
    templateId: 2,
    featured: false,
  },
]
